Part 1
Jocker34/Movie-app pull request #1
Opened 2022-09-25 23:05 UTC by Jocker34

2022-09-26 12:01 UTC, alexander-lozovsky requested changes

2022-09-26 12:01 UTC, alexander-lozovsky commented on package.json
> +    "eslint": "^8.24.0",
Please keep attention on this 
<img width="642" alt="image" src="https://user-images.githubusercontent.com/20779617/192269917-5e182aaa-f7ff-46dc-be57-ea572d9bf8e6.png">

CRA already installs eslint, you just need to configure it to run prettier https://github.com/prettier/eslint-plugin-prettier

please remove all unused eslint dependencies, and .eslintrc file as you have eslintConfig already in package.json

2022-09-26 12:01 UTC, alexander-lozovsky commented on package.json
> +    "webpack": "^5.74.0"
why do you need webpack here?

2022-09-27 09:02 UTC, EduardTrutsyk commented
could you please remove all unused/fake/test files and components to make it clean?

2022-09-27 12:19 UTC, Jocker34 commented on package.json
> +    "eslint": "^8.24.0",
done

2022-09-27 12:19 UTC, Jocker34 commented on package.json
> +    "webpack": "^5.74.0"
deleted

2022-09-27 12:44 UTC, alexander-lozovsky commented on package.json
> +    "babel-plugin-named-exports-order": "^0.0.2",
are you sure you need this?

2022-09-27 12:46 UTC, alexander-lozovsky commented on package.json
> +    "eslint-plugin-react-hooks": "^4.6.0",
from all those plugins you configured only 'prettier' and 'react'. So please remove all unused of configure them properly if you really need them

2022-09-27 12:53 UTC, RemZiQ commented on src/stories/Button.jsx
> +import React from 'react';
Hi, @Jocker34. I think we can also remove storybook examples excluding one that you prefer. With this approach, you will achieve more clear future PRs

2022-09-27 13:13 UTC, EduardTrutsyk approved these changes

2022-09-27 16:15 UTC, Jocker34 commented on package.json
> +    "babel-plugin-named-exports-order": "^0.0.2",
deleted

2022-09-27 16:15 UTC, Jocker34 commented on package.json
> +    "eslint-plugin-react-hooks": "^4.6.0",
deleted

2022-09-27 16:16 UTC, Jocker34 commented on src/stories/Button.jsx
> +import React from 'react';
deleted

2022-09-28 07:16 UTC, alexander-lozovsky approved these changes

2022-09-28 08:07 UTC, RemZiQ approved these changes

2022-09-28 15:54 UTC, merged