Part_2
Jocker34/Movie-app pull request #2
Opened 2022-10-02 23:47 UTC by Jocker34

2022-10-03 18:27 UTC, EduardTrutsyk commented on src/components/MovieCard/MovieCard.jsx
> +const Image = styled.div``;
why do you use div without any styles and call it `Image`?

2022-10-03 18:29 UTC, EduardTrutsyk commented on src/components/MoviePage/MoviePage.jsx
> +						<span>{LOREM}</span>
better to use single mock `json` file per page instead of multiple constants.
+ easy to remove
+ easy extend
+ single import

2022-10-03 18:30 UTC, EduardTrutsyk commented on src/common/Button/Button.jsx
> +		{buttonText}
I guess you can use a native prop for that: `children`

2022-10-03 18:31 UTC, EduardTrutsyk commented on src/common/Button/Button.jsx
> +		{buttonText}
anyway it should be removed and replaced by Button from material ui

2022-10-06 19:39 UTC, RemZiQ commented on src/common/Image/Image.jsx
> +	margin: 0 15px 0 15px;
From my point of view, a shared component should not use any margins. Consumers should decide will it contains these styles or not.

2022-10-06 19:39 UTC, RemZiQ commented on src/common/Input/Input.jsx
> +			<label htmlFor='input'>{labelText}</label>
Can we use MUI component instead?
https://mui.com/material-ui/react-text-field/#main-content

2022-10-06 19:39 UTC, RemZiQ commented on src/components/ActorPage/ActorPage.jsx
> +		<Container>
There are only 2 components imported. And other stuff is defined right on the page level. I think definitely a page should not contain such specific details of implementation and should be split into more generic components. I would like to suggest opening all mockups and thinking about how you can split pages into components and what of them could be reusable across the application. I am absolutely sure that it's not only Image and Input ;)

There are a lot of benefits to splitting your code
- clear and readable components
- components will be reusable if you will not brake at least `S` and `D` principles of SOLID
- easy testing


Try to think about the nearest future. Where are you going to put a data request?  How your page will look after adding more logic? Will it be single responsibility?

2022-10-06 19:39 UTC, RemZiQ commented on src/components/ActorPage/ActorPage.jsx
> +
Could you pls check the requirements for the project structure one more time?

2022-10-06 19:39 UTC, RemZiQ commented on src/components/ActorPage/ActorPage.jsx
> +						<h1>{translate(language).ACTOR_PAGE.PHOTOS}</h1>
Let's use `Typography` in all project

2022-10-06 19:39 UTC, RemZiQ commented on src/components/ActorPage/ActorPage.jsx
> +							</span>
`i. The page MUST be consisted of React components`

2022-10-06 19:39 UTC, RemZiQ commented on src/components/Header/Header.jsx
> +import styled from 'styled-components';
From my point of view, in most cases Header will be a reusable component across the application. Is it the correct folder?

2022-10-06 19:39 UTC, RemZiQ commented on src/components/Header/DropdownBar/DropdownBar.jsx
> +	const items = [
Please don't break `D` of SOLID.  This component should be reusable. And the reusable component should receive props of specific items.

2022-10-06 19:39 UTC, RemZiQ commented on src/components/Header/DropdownBar/DropdownBar.jsx
> +	color: white !important;
It's not a good practice to use `!important` without strong needs

2022-10-06 19:39 UTC, RemZiQ commented on src/components/Header/SerachBar/SerachBar.jsx
> +		<>
Unneeded Fragment here

2022-10-06 19:39 UTC, RemZiQ commented on src/components/MainPage/MainPage.jsx
> +	}, [active, count, indexOfFirstPost, indexOfLastPost, posts, search]);
I would like to suggest thinking about structure here.

Maybe a better option will be to achieve dependency only on `posts` for the level of defining existing items.

So possible structure can be

- fetch data/mock, define handlers for filtering, sorting, pagination, and memorize handlers
   - tabs/pagination UI receive handlers to trigger required action.
   - list of movies receive only posts


If you later somehow update the logic of fetching, filtering, sorting, and so on then your presentational components like tabs, pagination, or movie list will be not affected at all, they will receive new props and that's it.

2022-10-06 19:39 UTC, RemZiQ commented on src/components/MovieCard/Placeholder/Placeholder.jsx
> +			src={hover ? MovieHoverJPG : MoviePlaceholderIMG}
This can be done with CSS
https://developer.mozilla.org/en-US/docs/Web/CSS/:hover

2022-10-06 19:39 UTC, RemZiQ commented on src/components/MainPage/components/CategoriesTabs/CategoriesTabs.jsx
> +		if (index === 0) {
I understand that it's just a mock implementation, however, using indexes it's a bad practice. Also, don't brake single responsibility principle.  The logic of sorting can be defined on a higher level and passed via props handler to trigger sorting

2022-10-11 21:01 UTC, EduardTrutsyk commented on src/components/MainPage/components/CategoriesTabs/CategoriesTabs.jsx
> +				<Tabs
I guess you can use ToggleButton from MaterialUI instead of custom components
https://mui.com/material-ui/react-toggle-button/#color

2022-10-11 21:06 UTC, EduardTrutsyk commented on src/components/MoviePage/MoviePage.jsx
> +export const MoviePage = ({ language }) => {
we do not have requirements to support multi-languages in Part 2, but if you want to implement it right now, please avoid props drilling.
https://blog.logrocket.com/solving-prop-drilling-react-apps/

2022-10-11 21:15 UTC, EduardTrutsyk commented on src/components/MoviePage/MoviePage.jsx
> +							<span>{translate(language).MOVIE_PAGE.TITLE}</span>
to translate labels, the function should not return an object, because it's not possible to put arguments(for example: "{total} results found"), also it will be difficult to support, refactor and maintain. 
this function should take one or two arguments(key and data) and return the translated string.
The best way to use such libraries like `i18next`: https://react.i18next.com/
But it's not allowed to use for now, and translations are out of scope for Part 2.
But if you want to implement it, please use React Context for that.

2022-10-11 21:24 UTC, EduardTrutsyk commented on src/components/MoviePage/MoviePage.jsx
> +						<MovieCard key={movie.id} />
from my point of view, the `MovieCard` should have at least one prop `data` or `move`.
the `MovieCard` is a dump component and should be used only for presentations, to avoid redundant dependencies and support low coupling and high cohesion.

2022-10-11 21:28 UTC, EduardTrutsyk commented on src/components/MainPage/MainPage.jsx
> +const Movies = styled.div`
could you please reuse MaterialUI components as much as possible?
in this case, you can easily use `Grid` component:
https://mui.com/material-ui/react-grid/

2022-10-11 21:34 UTC, EduardTrutsyk commented on src/components/Header/Header.jsx
> +const HeaderContainer = styled.div`
I guess you can use `AppBar` and other Layout components from MaterialUI
https://mui.com/material-ui/react-app-bar/

2022-10-11 21:35 UTC, EduardTrutsyk commented on src/components/Header/Header.jsx
> +const Title = styled.h1`
please avoid custom components and use Material UI as much as possible.
feel free to customize the theme and components.

2022-10-11 21:36 UTC, EduardTrutsyk commented on src/components/Header/SerachBar/SerachBar.jsx
> +const StyledInput = styled(Input)`
same here

2022-10-11 21:49 UTC, EduardTrutsyk requested changes

2022-10-11 21:49 UTC, EduardTrutsyk commented on src/components/MainPage/MainPage.jsx
> +const StyledPagination = styled(Pagination)`
please review your PR by yourself and replace custom components with MaterialUI.
https://mui.com/material-ui/react-pagination/#main-content

2022-10-11 21:49 UTC, EduardTrutsyk commented on src/components/MainPage/components/CategoriesTabs/CategoriesTabs.jsx
> +const Container = styled.div`
please avoid custom components when it's possible

2022-10-11 21:49 UTC, EduardTrutsyk commented on src/components/MovieCard/MovieCard.jsx
> +const Raiting = styled.div`
is it possible to use `Badge` component?
https://mui.com/material-ui/react-badge/#main-content

2022-10-11 21:49 UTC, EduardTrutsyk commented on src/components/MoviePage/MoviePage.jsx
> +const Description = styled.div`
why are all of these components placed on the `MoviePage` level?
you need to read more about SOLID and how to separate components.
The main goal of the `Part 2` is to componentize the react application, reuse material UI and implement base page with some styles.
Please read and apply in practice:
[Componentizing our React app](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components)

2022-10-13 16:43 UTC, Jocker34 commented on src/components/MainPage/MainPage.jsx
> +const StyledPagination = styled(Pagination)`
But Pagination component is from MaterialUI. I just add some other style here

2022-10-17 11:33 UTC, EduardTrutsyk commented on src/common/Image/Image.jsx
> +		<div>
do you really need this wrapper?

2022-10-17 11:51 UTC, EduardTrutsyk requested changes

2022-10-17 11:51 UTC, EduardTrutsyk commented on src/components/ActorCard/ActorCard.jsx
> +		<ActorCardContainer>
looks like you are using tabs instead of spaces, which means that no integration with prettier.
could you please make sure that you have `prettier` integration with `lint-staged`

2022-10-17 11:51 UTC, EduardTrutsyk commented on src/pages/Header.jsx
> +					<Search>
from my point of view, the `SearchInput` can be a reusable and independent component. Why do you use `childer` prop for `SearchIcon`?

2022-10-17 11:51 UTC, EduardTrutsyk commented on src/pages/Header.jsx
> +const StyledInputBase = styled(InputBase)(({ theme }) => ({
are you sure that this is the best place for styles for `SearchInput`. 
Please read more deeply about React components composition.
 https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components

https://www.developerway.com/posts/components-composition-how-to-get-it-right

2022-10-17 11:51 UTC, EduardTrutsyk commented on src/pages/Header.jsx
> +const StyledInputBase = styled(InputBase)(({ theme }) => ({
please review PR by yourself, and when it will be ideal from your side, send it to review.

2022-10-17 11:51 UTC, EduardTrutsyk commented on src/pages/MainPage.jsx
> +					<Box sx={{ height: '100%' }}>
what is the purpose of memoization JSX?
please read about React reconciliation : https://reactjs.org/docs/reconciliation.html

2022-10-17 11:51 UTC, EduardTrutsyk commented on src/pages/actorPage/Description.jsx
> +					{translate(language).ACTOR_PAGE.NAME}
I guess you need to read more about React Context and prop drilling.

2022-10-17 23:05 UTC, EduardTrutsyk commented
[Styled Components Best Practices](https://www.robinwieruch.de/styled-components/)
[A Great Way to Use styled-components](https://www.pullrequest.com/blog/styled-components-best-practices/)

2022-10-19 21:15 UTC, Jocker34 commented on src/components/MoviePage/MoviePage.jsx
> +						<MovieCard key={movie.id} />
It will have i next Part. Right now i cant use API request.

2022-10-21 09:26 UTC, EduardTrutsyk requested changes

2022-10-21 09:26 UTC, EduardTrutsyk commented on src/App.jsx
> +    <>
do you really need fragment here?

2022-10-21 09:26 UTC, EduardTrutsyk commented on src/components/MovieCard/MovieCard.jsx
> +    <Container className={className}>
does it make sense to use `Card` component?

2022-10-21 09:26 UTC, EduardTrutsyk commented on src/components/MovieCard/MovieCard.jsx
> +          anchorOrigin={{
https://www.developerway.com/posts/react-re-renders-guide

2022-10-21 09:26 UTC, EduardTrutsyk commented on src/components/MovieCard/Placeholder/Placeholder.jsx
> +import MovieHoverJPG from 'images/MovieHover.jpg';
could you please remove this file, it can be archived with CSS only, also it does't make sense to use default image with play button, because the button is not clickable

2022-10-21 09:26 UTC, EduardTrutsyk commented on src/components/MovieCard/Placeholder/Placeholder.jsx
> +export const MoviePlaceholder = () => {
I'm not sure that you need MoviePlaceholder component, because usually you need to render image from api response, but if it's undefined, you can use the default placeholder.

2022-10-21 09:26 UTC, EduardTrutsyk commented on src/pages/moviePage/Description.jsx
> +          {translate(language).MOVIE_PAGE.TITLE}
please read more about `i18n`, this this incorrect way of using translation.

https://github.com/Jocker34/Movie-app/pull/2#discussion_r992785326

2022-10-21 09:26 UTC, EduardTrutsyk commented on src/pages/moviePage/Description.jsx
> +          {translate(language).MOVIE_PAGE.TITLE}
you are using React Context and helper function, but in ReactJs the combination of function and React stuff called React Hook:
https://reactjs.org/docs/hooks-intro.html

2022-10-21 09:28 UTC, EduardTrutsyk commented on src/pages/moviePage/Description.jsx
> +          {translate(language).MOVIE_PAGE.TITLE}
try to implement your own `useTranslation` hook without any helpers

2022-10-22 19:34 UTC, RemZiQ commented on src/pages/mainPage/Tabs.jsx
> +  const [alignment, setAlignment] = useState('');
Looks like it was copied and pasted from the documentation. Please take care about the meaning of naming

2022-10-22 19:34 UTC, RemZiQ commented on src/pages/mainPage/Tabs.jsx
> +  width: fit-content;
Why do we need `fit-content`?  As for me, it doesn't have any sense.

2022-10-22 19:34 UTC, RemZiQ commented on src/pages/mainPage/Tabs.jsx
> +  width: fit-content;
Also on a real project pay attention to the supported browsers list. You can use this one for check support
https://caniuse.com/?search=fit-content

2022-10-22 19:34 UTC, RemZiQ commented on src/helpers/sortMovies.js
> +export const sortMoviesBy = (element, index, posts, setPosts, setActive) => {
Do you still use this function?

2022-10-22 19:34 UTC, RemZiQ commented on src/pages/ActorPage.jsx
> +  margin-left: 30px;
The best practice will be to have a margin on both sides, especially it makes sense on small screens. Also, hardcoded width looks strange. May be you need here `max-width`?

2022-10-22 19:34 UTC, RemZiQ commented on src/pages/MoviePage.jsx
> +const Container = styled.div`
It looks very similar to Actor page. Styles are the same. Description component also looks very similar for Actor page and Movie page. Did you think about reusing?  Maybe it's not an issue and maybe some reason exists. But pls always remember when you are doing copy-paste then a very high possibility that you are doing something wrong. You can try to analyze your code again and answer yourself. Should something be moved to shared?

2022-10-22 19:34 UTC, RemZiQ commented on src/pages/moviePage/MovieImage.jsx
> +    backgroundColor: '#40b43c',
It's not a requirement of this part, it's not a requirement at all for this project. However, I strongly recommend using `theme` of MUI and avoiding hardcoded values. On a real project with MUI, I am almost 100% sure you will use `theme`. And it will be good to practice right now to be ready for it in the future. 

Think at least about 2 points
- how will be easy right now to implement `light` and `dark` theme in your application?
- how will be easy to apply to your application other colors, for example for accessibility cases?
- try to imagine that your customer said to you, the `success` color should be right now a bit different and should be changed
- will be helpful for this cases to have one source of truth and to change in one place?

2022-10-22 19:40 UTC, RemZiQ commented
The issue with height is still present. I **strongly** recommend **reviewing your own PR before sending it to review**. Also, I strongly recommend reading accurately about `height` and how calculated `100%`. Also pay attention to `min-height, max-height, min-width, max-width, vh, vw`

2022-10-28 16:36 UTC, Jocker34 commented on src/components/MovieCard/Placeholder/Placeholder.jsx
> +export const MoviePlaceholder = () => {
After use new mock data i render button here with image form api

2022-10-28 16:43 UTC, Jocker34 commented on src/components/MovieCard/MovieCard.jsx
> +    <Container className={className}>
Why not? This is a card showing a video on the main page with information from the mock up and in the future from the api

2022-10-28 17:28 UTC, Jocker34 commented on src/pages/MoviePage.jsx
> +const Container = styled.div`
I've been thinking about it too. At the moment they have a few differences. The moment I add api queries if they still look the same I will merge them

2022-10-28 18:03 UTC, Jocker34 commented on src/pages/moviePage/MovieImage.jsx
> +    backgroundColor: '#40b43c',
Okey i will try replace on theme

2022-10-29 15:01 UTC, EduardTrutsyk commented on src/components/Header.jsx
> +        backgroundColor: '#282424',
I guess you can override MaterialUI theme: https://mui.com/material-ui/customization/theming/

2022-10-29 15:01 UTC, EduardTrutsyk commented on src/components/Header.jsx
> +          <DropdownBar />
the name of the component is confusing, looks like this is not a reusable `Dropdown` component, but `LanguageDropdown` or something like that.

2022-10-29 15:01 UTC, EduardTrutsyk commented on src/components/header/DropdownBar.jsx
> +import { useTranslation } from 'helpers/useTranslation';
please do not use `helpers` folder for React Hooks to avoid confusion.

2022-10-29 15:01 UTC, EduardTrutsyk commented on src/components/movieCard/Placeholder.jsx
> +            ? `https://image.tmdb.org/t/p/w500${image}`
why do you use landscape image?

2022-10-29 15:01 UTC, EduardTrutsyk commented on src/components/movieCard/Placeholder.jsx
> +        alt={ALT.MOVIE}
what is the purpose of using `alt` attribute for image tag?

2022-10-29 15:01 UTC, EduardTrutsyk commented on src/components/movieCard/Placeholder.jsx
> +      <StyledButton
looks like it can be independent reusable component.

2022-10-29 15:01 UTC, EduardTrutsyk commented on src/constants.js
> +export const CATEGORIES = ['Popular', 'Top rated', 'Upcoming'];
how many times do you use this constant?

2022-10-29 15:01 UTC, EduardTrutsyk commented on src/constants.js
> +export const ITEMS = [
1. https://en.wikipedia.org/wiki/Naming_convention_(programming)
2. how many times do you use this constant?

2022-10-29 15:01 UTC, EduardTrutsyk commented on src/constants.js
> +    value: 'PL',
for language options better to use the following format to support dialects:
```
{
  code: 'en-US',
  label: 'English (US)'
}
```

2022-10-29 15:01 UTC, EduardTrutsyk commented on src/constants.js
> +export const PERSON_PHOTOS = [
please do not mix constants and mocks because you can forget to remove it in future when you will use real api. better to store mocks closer to the component which use these mocks.

2022-10-29 15:01 UTC, EduardTrutsyk commented on src/constants.js
> +export const MOVIE_PHOTO = [
same here, but better to use mocks similar to real data.

2022-10-29 15:01 UTC, EduardTrutsyk commented on src/constants.js
> +export const IMAGES = [
same here

2022-10-30 13:15 UTC, EduardTrutsyk requested changes

2022-10-30 13:15 UTC, EduardTrutsyk commented on src/pages/MainPage.jsx
> +  margin: 30px 25px 0 25px;
I guess you can avoid this styles by using `Grid`

2022-10-30 13:15 UTC, EduardTrutsyk commented on src/components/MainPage/MainPage.jsx
> +const Movies = styled.div`
not resolved yet

2022-10-30 13:15 UTC, EduardTrutsyk commented on src/components/MainPage/components/CategoriesTabs/CategoriesTabs.jsx
> +const Container = styled.div`
https://mui.com/material-ui/react-container/

2022-10-30 13:15 UTC, EduardTrutsyk commented on src/pages/MainPage.jsx
> +const Movies = styled.div`
why are all of these components placed on the MoviePage level?
you need to read more about SOLID and how to separate components.
The main goal of the Part 2 is to componentize the react application, reuse material UI and implement base page with some styles.
Please read and apply in practice:
[Componentizing our React app](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components)

Please do not ignore my comments, I can't leave comment for each component:
https://github.com/Jocker34/Movie-app/pull/2#discussion_r992806542

2022-10-30 13:15 UTC, EduardTrutsyk commented on src/pages/MainPage.jsx
> +const StyledPagination = styled(Pagination)`
if you want to change styles for Material UI components, please try to do it via `theme`, to be able to reuse this component with the same styles.
https://mui.com/material-ui/customization/theming/

or you can create your own component base on Material UI.

2022-11-15 23:53 UTC, Jocker34 commented on src/pages/MainPage.jsx
> +  margin: 30px 25px 0 25px;
In this case, I would prefer to leave it as it is. Grid makes it more unreadable and produces many problems

2022-11-16 00:17 UTC, Jocker34 commented on src/constants.js
> +export const ITEMS = [
I changed the name and moved the mock to a different location so as not to mix it with constans

2022-11-16 00:17 UTC, Jocker34 commented on src/constants.js
> +export const PERSON_PHOTOS = [
same as above

2022-11-16 00:17 UTC, Jocker34 commented on src/constants.js
> +export const MOVIE_PHOTO = [
same as above

2022-11-16 00:19 UTC, Jocker34 commented on src/pages/MainPage.jsx
> +const Movies = styled.div`
It does not ignore comments. I changed the entire structure of the file and components. On top of that, the structure of the project was changed. In my opinion, it is now well done, so I resolved the thread

2022-11-16 00:27 UTC, Jocker34 commented on src/constants.js
> +export const IMAGES = [
same as above

2022-11-20 21:07 UTC, RemZiQ commented on src/pages/MainPage.jsx
> +        <Grid container justifyContent='center' sx={{ minHeight: '80vh' }}>
It fixes the issue with height. But let's think about something better.  What will be if I as a part of development team in this project will update styles of `Header`? Let's say I will update the height of it. Please try to find a more accurate solution. But you are on the right way

2022-11-20 21:07 UTC, RemZiQ commented on src/pages/MainPage.jsx
> +        <Grid container justifyContent='center' sx={{ minHeight: '80vh' }}>
Also with this solution scroll will be added without any needs


![image](https://user-images.githubusercontent.com/43277312/202921800-2dafaf28-2b2c-42fe-93d0-25e01e4121e5.png)

2022-11-20 21:07 UTC, RemZiQ commented on src/components/MovieCard.jsx
> +    <Container className={className}>
Is this prop used?

2022-11-20 21:07 UTC, RemZiQ commented on src/pages/actorPage/KnowBy.jsx
> +            <MovieCard key={movie.id} />
What is the reason to use `key` here?
https://reactjs.org/docs/lists-and-keys.html

2022-11-20 21:07 UTC, RemZiQ commented on src/pages/actorPage/KnowBy.jsx
> +  fontWeight: 'bold',
Please accurately check styles, and think about the reasons to use rules and which are really needed.

2022-11-20 21:07 UTC, RemZiQ commented on src/pages/MainPage.jsx
> +  display: 'flex',
You have a lot of duplications with `display: flex`. `Grid` component is created for it. What problems do you think it can bring? Also please note that you can use nested `Grid`
https://mui.com/material-ui/react-grid/#NestedGrid.js

2022-11-20 21:07 UTC, RemZiQ commented on src/pages/MainPage.jsx
> +  display: 'flex',
Please check all the same places and replace them with `Grid`.

2022-11-20 21:07 UTC, RemZiQ commented on src/pages/MainPage.jsx
> +  color: 'white',
In case we have an agreement to use `theme`, please avoid the hardcoded values. Please update all places with the same issues.

2022-11-20 21:07 UTC, RemZiQ commented on src/pages/MoviePage.jsx
> +  margin: 0 30px 0 30px;
You can use shorthand
https://developer.mozilla.org/en-US/docs/Web/CSS/margin

2022-11-20 21:07 UTC, RemZiQ commented on src/pages/actorPage/Description.jsx
> +  color: 'white',
With `sx` you can still get access to `theme` and avoid hardcode
https://mui.com/system/getting-started/the-sx-prop/

2022-11-20 21:07 UTC, RemZiQ commented on src/pages/actorPage/Photos.jsx
> +  m: 1,
Please check for unneeded styles. Do you think it's the correct naming with take to attention applied rules?

2022-11-20 21:07 UTC, RemZiQ commented on src/pages/moviePage/Images.jsx
> +  fontWeight: 'bold',
Pls check styles and naming

2022-11-20 21:07 UTC, RemZiQ commented on src/pages/moviePage/Recommendations.jsx
> +  fontWeight: 'bold',
Please check styles

2022-11-20 21:07 UTC, RemZiQ commented on src/components/ActorCard.jsx
> +    <Container>
It's bad practice to add a wrapper just for styling, instead of this responsible element should be styled.

Do you see how many duplications of color in the project? Maybe a good solution will be to override typography globally with white color by default.

![image](https://user-images.githubusercontent.com/43277312/202924985-db6b4a15-ed39-41ac-814d-54e5b3798c8b.png)

2022-11-20 21:07 UTC, RemZiQ commented on src/constants.js
> +export const CATEGORIES = ['Popular', 'Top rated', 'Upcoming'];
@Jocker34, why do you ignore it? Please don't do this with our comments. We are spending our time helping you to grow, please respect it

2022-11-20 21:07 UTC, RemZiQ commented on src/pages/MoviePage.jsx
> +  margin: 0 30px 0 30px;
I reviewed these styles one more time. You didn't add `margin` on the bottom of the pages.

2022-12-06 23:06 UTC, Jocker34 commented on src/components/MovieCard.jsx
> +    <Container className={className}>
Inside this component not, but it needed to change style form paretns component. "styled can style any component as long as it accepts a className prop"

2022-12-06 23:43 UTC, Jocker34 commented on src/pages/actorPage/KnowBy.jsx
> +            <MovieCard key={movie.id} />
You are right. In MovieCard, the key is unnecessary. I have removed it in other similar places.

2022-12-06 23:46 UTC, Jocker34 commented on src/pages/actorPage/KnowBy.jsx
> +  fontWeight: 'bold',
I checked all the styles. I tried to remove all unnecessary styles and replaced with grids where possible. I also went through the names of the styles and changed the

2022-12-06 23:47 UTC, Jocker34 commented on src/pages/MainPage.jsx
> +  display: 'flex',
I checked all the styles. I tried to remove all unnecessary styles and replaced with grids where possible. I also went through the names of the styles and changed the

2022-12-06 23:47 UTC, Jocker34 commented on src/pages/actorPage/Photos.jsx
> +  m: 1,
I checked all the styles. I tried to remove all unnecessary styles and replaced with grids where possible. I also went through the names of the styles and changed the

2022-12-06 23:47 UTC, Jocker34 commented on src/pages/moviePage/Images.jsx
> +  fontWeight: 'bold',
I checked all the styles. I tried to remove all unnecessary styles and replaced with grids where possible. I also went through the names of the styles and changed the

2022-12-06 23:47 UTC, Jocker34 commented on src/pages/moviePage/Recommendations.jsx
> +  fontWeight: 'bold',
I checked all the styles. I tried to remove all unnecessary styles and replaced with grids where possible. I also went through the names of the styles and changed the

2022-12-06 23:50 UTC, Jocker34 commented on src/constants.js
> +export const CATEGORIES = ['Popular', 'Top rated', 'Upcoming'];
Actually I didn't notice that I don't even use it. My mistake sorry for deleting the comment and not making the change. The array has been removed

2022-12-08 15:44 UTC, EduardTrutsyk requested changes

2022-12-08 15:44 UTC, EduardTrutsyk commented on src/components/MovieCard.jsx
> +    <Card variant='outlined' sx={style} className={className}>
could you please use only one approach for styling components?
it's recommended to use `styled` in some cases `sx`, but please avoid of using `className`
https://mui.com/material-ui/customization/how-to-customize/#1-one-off-customization

2022-12-08 15:44 UTC, EduardTrutsyk commented on src/components/header/LanguageDropdown .jsx
> +  margin: 20px 85px 20px 0;
could you please avoid such a huge margin for reusable components?

2022-12-08 15:44 UTC, EduardTrutsyk commented on src/components/header/SearchBar.jsx
> +    e.target.value ? setSearch(e.target.value) : setSearch('');
could you please try to void the ternary operator due to cognitive complexity

2022-12-08 15:44 UTC, EduardTrutsyk commented on src/components/movieCard/Placeholder.jsx
> +const Container = styled.div``;
could you please explain why you use the styled component without any styles?

2022-12-08 15:44 UTC, EduardTrutsyk commented on src/helpers/languageContext.js
> +const LanguageContext = React.createContext({
could you please more React `Context` components to `context` directory instead of `helpers`.

2022-12-08 15:44 UTC, EduardTrutsyk commented on src/helpers/translation.js
> +  PL: {
from my point of view, it makes sense to move translations to separate files for each locale. 
also please move it outside the `helpers` directory.

2022-12-08 15:44 UTC, EduardTrutsyk commented on src/index.css
> +    background-color: #181414;
could you please special component from MaterialUI instead of `index.css` and customize `theme` to change the page background color?

2022-12-08 15:44 UTC, EduardTrutsyk commented on src/mocks.js
> +    id: 1,
you can achieve the same result with one line of code instead of manually hardcode similar objects

2022-12-08 15:44 UTC, EduardTrutsyk commented on src/mocks.js
> +    id: 1,
same here

2022-12-08 15:44 UTC, EduardTrutsyk commented on src/pages/MainPage.jsx
> +          {searchMovie(posts, search, indexOfFirstPost, indexOfLastPost).map(
the result of this function can be stored in a separate variable and reused instead of calling this function two times in the same file

2022-12-08 15:44 UTC, EduardTrutsyk commented on src/pages/MainPage.jsx
> +          onChange={(e) => handleOnChange(e.target.textContent)}
`onChange={handleOnChange}`

2022-12-08 15:44 UTC, EduardTrutsyk commented on src/pages/MainPage.jsx
> +      <h1>NO RESULTS FOUND</h1>
please use `Typography` component for text formatting

2022-12-08 15:44 UTC, EduardTrutsyk commented on src/pages/MainPage.jsx
> +const StyledPagination = styled(Pagination)(({ theme }) => ({
does it make sense to move it `component` directory and reuse it in the future?
could you please avoid placing multiple components in one file?

2022-12-10 20:50 UTC, RemZiQ commented on src/pages/MoviePage.jsx
> +  margin: 0 30px 0 30px;
You can use shorthand
https://developer.mozilla.org/en-US/docs/Web/CSS/margin

2022-12-10 20:50 UTC, RemZiQ commented on src/components/MovieCard.jsx
> +    <Container className={className}>
I see. You are redefining styles for MovieCard. Thanks for explanation

2022-12-10 20:50 UTC, RemZiQ commented on src/components/MovieCard/MovieCard.jsx
> +    <Container className={className}>
I think Eduard told about this [one](https://mui.com/material-ui/react-card/) and not about naming

2022-12-10 20:50 UTC, RemZiQ commented on src/pages/MainPage.jsx
> +        <Grid container justifyContent='center' sx={{ minHeight: '80vh' }}>
Did you fix it?

2022-12-15 09:08 UTC, EduardTrutsyk requested changes

2022-12-15 09:08 UTC, EduardTrutsyk commented on src/components/MovieCard.jsx
> +    <Card variant='outlined' sx={style} className={className}>
looks like you do not use `className` anymore, I guess it can be removed

2022-12-15 09:08 UTC, EduardTrutsyk commented on src/components/Header.jsx
> +  backgroundColor: theme.palette.grey[900],
could you please customize deefault`theme` to avoid custom styles and increase reusability? 
because each time when you will use `AppBar` you need to write custom styles.
You can use one of the following options to achieve the same result:
1. override `palette.background.paper` to override all "paper" backgrounds: https://mui.com/material-ui/customization/default-theme/#explore
2. override styles for specific component via `theme`: https://mui.com/material-ui/customization/theme-components/#global-style-overrides
3. create a custom `AppBar` component and override styles for that. (not recommended if one of the options above is applicable)

2022-12-15 09:08 UTC, EduardTrutsyk commented on src/components/movieCard/Placeholder.jsx
> +const Container = styled.div``;
not resolved yet

2022-12-15 09:08 UTC, EduardTrutsyk commented on src/localization/translation.js
> +  PL: { ...POLISH },
what is the purpose of spreading one object to another without any modifications?

2022-12-15 09:08 UTC, EduardTrutsyk commented on src/mocks.js
> +    id: 1,
tip: you can use `Array(8)`, something else and `map`

2022-12-15 09:08 UTC, EduardTrutsyk commented on src/pages/MainPage.jsx
> +const StyledPagination = styled(Pagination)(({ theme }) => ({
not resolved yet

2022-12-15 09:08 UTC, EduardTrutsyk commented on src/pages/MainPage.jsx
> +  margin: '30px 20px 0 20px',
you can avoid these custom styles by using `Grid`: https://mui.com/material-ui/react-grid/#main-content

2022-12-15 09:08 UTC, EduardTrutsyk commented on src/pages/MoviePage.jsx
> +  margin: 0 30px 0 30px;
not resolved yet

2022-12-15 09:08 UTC, EduardTrutsyk commented on src/pages/actorPage/KnowBy.jsx
> +        {mockMoviePhoto.map((movie) => (
Duplicate logic: 
1. https://github.com/Jocker34/Movie-app/pull/2/files#diff-7215d4ca408de403cb14dea52223a27ad25875b5e818a36395fcf9cd28999349R42
2. https://github.com/Jocker34/Movie-app/pull/2/files#diff-712d0737b0b356450c4eec8d5dcd443abf3ab1ab53aeebac5c739dea4df39530R20

I guess makes sense to create a reusable component `<MoviCardList data={movies} />` or something like that to avoid duplication.

2022-12-15 09:08 UTC, EduardTrutsyk commented on src/pages/mainPage/Tabs.jsx
> +  backgroundColor: theme.palette.common.white,
does it make sense to override styles for `ToggleButtonGroup` component globally to keep consistency across all application? 
https://mui.com/material-ui/customization/theme-components/#global-style-overrides

2022-12-15 09:08 UTC, EduardTrutsyk commented on src/pages/moviePage/Description.jsx
> +  padding-bottom: 30px;
please use `Grid` component in the right way, not only `container` but `item` as well to avoid custom styles.
https://mui.com/material-ui/react-grid/#main-content

2022-12-15 09:08 UTC, EduardTrutsyk commented on src/theme.js
> +          backgroundColor: '#181414',
could you please override `theme.palette.background.default` instead of global style overrides?

2022-12-15 09:08 UTC, EduardTrutsyk commented on src/theme.js
> +          color: 'white',
to customize text color you can override `theme.palette.text.main` color.
https://mui.com/material-ui/customization/default-theme/#explore

2022-12-15 09:08 UTC, EduardTrutsyk commented on src/pages/moviePage/Recommendations.jsx
> +        {mockMoviePhoto.map((movie) => (
please reuse the `MoviCardList` component mentioned above.

2022-12-15 09:44 UTC, Jocker34 commented on src/pages/actorPage/Description.jsx
> +  color: 'white',
Corrected. I now use the theme everywhere possible

2022-12-15 09:44 UTC, Jocker34 commented on src/pages/MoviePage.jsx
> +  margin: 0 30px 0 30px;
I don't understand. I'm using a shortcut and why do I need the margin bottom ?

2022-12-15 09:44 UTC, Jocker34 commented on src/components/movieCard/Placeholder.jsx
> +      <StyledButton
This is an independent component from the MUI library

2022-12-15 09:44 UTC, Jocker34 commented on src/components/ActorCard.jsx
> +    <Container>
I removed the wrapper and checked if I had not done so in similar places. I applied the styles directly to the needed places. The idea of overwriting typography is also a good one. I applied it

2022-12-15 09:44 UTC, Jocker34 commented on src/pages/MainPage.jsx
> +        <Grid container justifyContent='center' sx={{ minHeight: '80vh' }}>
As I understand the best way is use  calculated 100% on every element

2022-12-15 09:44 UTC, Jocker34 commented on src/components/header/SearchBar.jsx
> +    e.target.value ? setSearch(e.target.value) : setSearch('');
Repleced to if statment

2022-12-15 09:44 UTC, Jocker34 commented on src/components/movieCard/Placeholder.jsx
> +const Container = styled.div``;
Because I need a container to use as a selector in the hover for the button and image below

2022-12-15 09:44 UTC, Jocker34 commented on src/helpers/languageContext.js
> +const LanguageContext = React.createContext({
I created a context folder and moved the file there

2022-12-15 09:44 UTC, Jocker34 commented on src/pages/MainPage.jsx
> +const StyledPagination = styled(Pagination)(({ theme }) => ({
I'm a little confused with this comment. This is a component with MUI, we just change the style of some css.

2022-12-15 09:44 UTC, Jocker34 commented on src/pages/MainPage.jsx
> +      <h1>NO RESULTS FOUND</h1>
Corrected

2022-12-15 09:44 UTC, Jocker34 commented on src/pages/MainPage.jsx
> +          {searchMovie(posts, search, indexOfFirstPost, indexOfLastPost).map(
Corrected

2022-12-15 09:44 UTC, Jocker34 commented on src/pages/MainPage.jsx
> +          onChange={(e) => handleOnChange(e.target.textContent)}
corrected

2022-12-15 09:44 UTC, Jocker34 commented on src/helpers/translation.js
> +  PL: {
corrected, created folder and move splitted files

2022-12-15 09:44 UTC, Jocker34 commented on src/components/MovieCard.jsx
> +    <Card variant='outlined' sx={style} className={className}>
I need to provide className for the wrapper/container when i add extra style form parent level.

2022-12-15 09:44 UTC, Jocker34 commented on src/pages/MoviePage.jsx
> +  margin: 0 30px 0 30px;
I still don't understand where the problem lies. Maybe you are looking into old code. I am using the shortcut ` margin: 0 30px 0 30px;`
![obraz](https://user-images.githubusercontent.com/36955398/207737924-cadd0b30-692d-462e-b658-85ea1c278e81.png)

2022-12-15 09:44 UTC, Jocker34 commented on src/pages/MainPage.jsx
> +  color: 'white',
corrected

2022-12-15 09:44 UTC, Jocker34 commented on src/index.css
> +    background-color: #181414;
Corrected

2022-12-15 09:44 UTC, Jocker34 commented on src/mocks.js
> +    id: 1,
I can just create an array with a few elements, but it will be removed in the next part and I will use the api request, so I think it is not an import.

2022-12-15 09:44 UTC, Jocker34 commented on src/mocks.js
> +    id: 1,
I can just create an array with a few elements, but it will be removed in the next part and I will use the api request, so I think it is not an import.

2022-12-15 09:44 UTC, Jocker34 commented on src/components/header/LanguageDropdown .jsx
> +  margin: 20px 85px 20px 0;
After thinking about it, it is not even needed. it has been removed

2022-12-15 09:44 UTC, Jocker34 commented on src/pages/MainPage.jsx
> +        <Grid container justifyContent='center' sx={{ minHeight: '80vh' }}>
I honestly have no idea how to do it differently anymore. Right now I can remove the pixel width from the header so there is no scroll. I also looked at other sites of this type and the pagination is always glued to the results. So I removed the width, and thanks to the generic background there is no white square

2022-12-15 09:44 UTC, Jocker34 commented on src/components/MovieCard/MovieCard.jsx
> +    <Container className={className}>
This component has been recontracted. It is already used Card with mui

2022-12-15 10:04 UTC, EduardTrutsyk commented on src/components/MovieCard.jsx
> +    <Card variant='outlined' sx={style} className={className}>
> 

please follow KISS and YAGNI principles

2022-12-16 17:37 UTC, Jocker34 commented on src/components/movieCard/Placeholder.jsx
> +const Container = styled.div``;
I removed the styled and added an id to the div so I could control the hover

2022-12-16 17:37 UTC, Jocker34 commented on src/localization/translation.js
> +  PL: { ...POLISH },
You're right, it was redundant. Corrected

2022-12-16 17:37 UTC, Jocker34 commented on src/theme.js
> +          color: 'white',
Corrected

2022-12-16 17:37 UTC, Jocker34 commented on src/theme.js
> +          backgroundColor: '#181414',
Corrected

2022-12-16 17:37 UTC, Jocker34 commented on src/components/Header.jsx
> +  backgroundColor: theme.palette.grey[900],
I chose option two with oerrride style for specific component

2022-12-16 17:37 UTC, Jocker34 commented on src/mocks.js
> +    id: 1,
Corrected

2022-12-16 17:37 UTC, Jocker34 commented on src/mocks.js
> +    id: 1,
Corrected

2022-12-16 17:37 UTC, Jocker34 commented on src/components/MovieCard.jsx
> +    <Card variant='outlined' sx={style} className={className}>
className is no longer needed. Removed

2022-12-16 17:37 UTC, Jocker34 commented on src/pages/MainPage.jsx
> +  margin: '30px 20px 0 20px',
Corrected

2022-12-16 17:37 UTC, Jocker34 commented on src/pages/actorPage/KnowBy.jsx
> +        {mockMoviePhoto.map((movie) => (
Corrected

2022-12-16 17:37 UTC, Jocker34 commented on src/pages/moviePage/Recommendations.jsx
> +        {mockMoviePhoto.map((movie) => (
Corrected

2022-12-16 17:37 UTC, Jocker34 commented on src/pages/MoviePage.jsx
> +  margin: 0 30px 0 30px;
I removed the styles and replaced the grid

2022-12-16 17:37 UTC, Jocker34 commented on src/pages/moviePage/Description.jsx
> +  padding-bottom: 30px;
Corrected

2022-12-16 17:37 UTC, Jocker34 commented on src/pages/mainPage/Tabs.jsx
> +  backgroundColor: theme.palette.common.white,
Yes you are right it makes sense. Corrected

2022-12-16 17:37 UTC, Jocker34 commented on src/pages/MainPage.jsx
> +const StyledPagination = styled(Pagination)(({ theme }) => ({
I further do not understand the comment. Pagination is not my component only from MUI library. Just adds some new styles to it. Can you elaborate on your thought?

2022-12-19 09:05 UTC, EduardTrutsyk commented on src/components/movieCard/Placeholder.jsx
> +const Container = styled.div``;
I guess you can use `div` or `React.Fragment` directly instead of an empty styled component.

2022-12-19 09:05 UTC, EduardTrutsyk commented on src/mocks.js
> +    id: 1,
Anyway, we need to write less code as possible but achieve the same result. 
it can be skipped for now, but in the future, for production code, you need to follow this rule, because there is less code - fewer bugs and tests.

2022-12-19 09:05 UTC, EduardTrutsyk commented on src/mocks.js
> +    id: 1,
```js
Array(4).fill().map((_, i) => ({id: i+1}));
```

2022-12-19 09:05 UTC, EduardTrutsyk commented on src/pages/MainPage.jsx
> +const StyledPagination = styled(Pagination)(({ theme }) => ({
1. this component is placed in `MainPage` file, what will you do when you need to add pagination on the `ActorPage` for actor`s movies?

2022-12-19 09:05 UTC, EduardTrutsyk commented on src/pages/MoviePage.jsx
> +  margin: 0 30px 0 30px;
this is not a shortcut:
![image](https://user-images.githubusercontent.com/5457280/207855963-86a2628b-232e-4e6a-83c6-acdbbf7bbe67.png)

But on the official doc the first of three examples uses a shortcut:
![image](https://user-images.githubusercontent.com/5457280/207856390-03b7931f-06d8-48ac-9d2a-b62f9a71e729.png)

in your case, if can achieve the same result with the following line:
```css
margin: 0 30px
```

2022-12-19 09:05 UTC, EduardTrutsyk commented on src/pages/MainPage.jsx
> +const StyledPagination = styled(Pagination)(({ theme }) => ({
correct, but next time when you will use the `Pagination` component you will copy\paste the styles because this component is placed in `MainPage` file, but not in the `components` directory. It's ok for now, I will remind you about this case in your next PR ;)

2022-12-19 09:07 UTC, EduardTrutsyk approved these changes

2022-12-19 13:01 UTC, RemZiQ commented on src/pages/MainPage.jsx
> +        <Grid container justifyContent='center' sx={{ minHeight: '80vh' }}>
Hey @Jocker34,

The solution is very easy. I just tried to make you find it by yourself. Instead of using 80vh in the nested component, you could apply min-height: 100vh on the page wrapper level. With this approach, you will have 100vh in case of lacking items (ofcourse block with items should be scaling on all available height). Your page will absolutely don't care about height of header or another component used with hardcoded sizes, in other words, you will achieve adaptivity. And on another hand scroll will be added only when the amount of items is too big for 100vh.

So default approach can be:
-  minHeight100vh container
- stretch nested component on available height

Example:
https://codepen.io/RemZiK/pen/vYaYZYB

2022-12-19 13:01 UTC, RemZiQ commented on src/pages/MainPage.jsx
> +        <Grid container justifyContent='center' sx={{ minHeight: '80vh' }}>
![image](https://user-images.githubusercontent.com/43277312/208432064-403fa36d-03a5-4af2-994a-b04a1067b3db.png)

2022-12-19 13:25 UTC, RemZiQ commented on src/components/MoviCardList.jsx
> +        <Grid key={post.id || post} item>
Looks strange. Id should be required field. Please use `map` for your mock and add id.

2022-12-19 13:29 UTC, RemZiQ commented on src/components/movieCard/Placeholder.jsx
> +    <div id='wrapper'>
Using id for styles is a bad practice

2022-12-19 15:02 UTC, RemZiQ approved these changes

2022-12-19 15:02 UTC, merged

2023-01-17 23:22 UTC, Jocker34 commented on src/components/MoviCardList.jsx
> +        <Grid key={post.id || post} item>
Right, corrected. After adding the API data, the problem solved itself

2023-01-17 23:22 UTC, Jocker34 commented on src/components/movieCard/Placeholder.jsx
> +    <div id='wrapper'>
I will restore the previous solution

2023-01-17 23:25 UTC, Jocker34 commented on src/pages/MainPage.jsx
> +        <Grid container justifyContent='center' sx={{ minHeight: '80vh' }}>
In fact, it came out even simpler than your example. Thank you for your help